---

  - name: Install and Configure rsyslog
    hosts: debian
    remote_user: admin
    become: yes
    become_user: root
    vars:
      sl1_mc: "change_me"
    tasks:

      - name: Update apt repo and cache
        apt: 
          update_cache: yes 
          upgrade: dist
          autoremove: yes
          force_apt_get: yes 
          cache_valid_time: 3600

      - name: Ensure rsyslog is installed
        apt:
          name: 
            - rsyslog
          state: present
          update_cache: true

      - name: Add our rsyslog.conf line
        ansible.builtin.lineinfile:
          path: /etc/rsyslog.conf
          owner: root
          group: root
          mode: '0600'
          line: '*.*  action(type="omfwd" target="{{ sl1_mc }}" port="514" protocol="udp"'
          insertafter: EOF

      - name: Add our rsyslog.conf line
        ansible.builtin.lineinfile:
          path: /etc/rsyslog.conf
          owner: root
          group: root
          mode: '0600'
          line: '            action.resumeRetryCount="100"'
          insertafter: EOF

      - name: Add our rsyslog.conf line
        ansible.builtin.lineinfile:
          path: /etc/rsyslog.conf
          owner: root
          group: root
          mode: '0600'
          line: '            queue.type="linkedList" queue.size="10000")'
          insertafter: EOF

      - name: Reload and restart rsyslog
        ansible.builtin.systemd:
          name: rsyslog
          enabled: yes
          daemon_reload: yes
          state: restarted
