---

  - name: Install and Configure SNMP
    hosts: centos
    remote_user: centos
    become: yes
    become_user: root
    vars:
      snmp_ro: "change_me"
      sl1_dc: "change_me"
      sl1_mc: "change_me"
    tasks:

      - name: Install the latest version of snmpd
        ansible.builtin.yum:
          name: net-snmp
          state: latest

      - name: Add our snmpd.conf
        ansible.builtin.copy:
          src: /opt/ansible/default_files/snmpd.conf
          dest: /etc/snmp/snmpd.conf
          owner: root
          group: root
          mode: '0600'

      - name: Replace default snnm RO string with variable from playbook
        ansible.builtin.replace:
          path: /etc/snmp/snmpd.conf
          regexp: 'snmp_ro'
          replace: '{{ snmp_ro }}'

      - name: Replace our placeholder Data Collector junk
        ansible.builtin.replace:
          path: /etc/snmp/snmpd.conf
          regexp: 'SL1_DC'
          replace: '{{ sl1_dc }}'

      - name: Replace our placeholder Message Collector junk 
        ansible.builtin.replace:
          path: /etc/snmp/snmpd.conf
          regexp: 'SL1_MC'
          replace: '{{ sl1_mc }}'

      - name: Reload and restart snmpd
        ansible.builtin.systemd:
          name: snmpd
          enabled: yes
          daemon_reload: yes
          state: restarted
